package oss

const (
	OS_windows   = "windows"
	OS_linux     = "linux"
	OS_solaris   = "solaris"
	OS_plan9     = "plan9"
	OS_openbsd   = "openbsd"
	OS_netbsd    = "netbsd"
	OS_js        = "js"
	OS_ios       = "ios"
	OS_illumos   = "illumos"
	OS_hurd      = "hurd"
	OS_freebsd   = "freebsd"
	OS_dragonfly = "dragonfly"
	OS_darwin    = "darwin"
	OS_android   = "android"
	OS_aix       = "aix"

	ARCH_wasm        = "wasm"
	ARCH_sparc64     = "sparc64"
	ARCH_sparc       = "sparc"
	ARCH_s390x       = "s390x"
	ARCH_s390        = "s390"
	ARCH_riscv64     = "riscv64"
	ARCH_riscv       = "riscv"
	ARCH_ppc64le     = "ppc64le"
	ARCH_ppc64       = "ppc64"
	ARCH_ppc         = "ppc"
	ARCH_mipsle      = "mipsle"
	ARCH_mips64p32le = "mips64p32le"
	ARCH_mips64p32   = "mips64p32"
	ARCH_mips64le    = "mips64le"
	ARCH_mips64      = "mips64"
	ARCH_mips        = "mips"
	ARCH_armbe       = "armbe"
	ARCH_arm64be     = "arm64be"
	ARCH_arm64       = "arm64"
	ARCH_arm         = "arm"
	ARCH_amd64       = "amd64"
	ARCH_386         = "386"
)
